name: "new-issue"
on:
  issues:
    types: [opened, edited]
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        label: 'bug'
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
  display-message-missing:
    runs-on: ubuntu-latest
    needs: [triage]
    steps:
      - uses: actions/checkout@v2.0.0 
      - name: issue comment
        id: issue_comment_missing
        uses: ./
        with: 
          repo-token: ${{ secrets.GITHUB_TOKEN}}
          label: 'More Information Required'
          message: >
            Your issue is missing required information from the [bug template](https://github.com/forcedotcom/cli/blob/main/.github/ISSUE_TEMPLATE/bug_report.md). When you provide us this information we'll triage and reproduce the issue.
      - name: default comment
        id: issue_comment
        uses: ./
        with: 
          repo-token: ${{ secrets.GITHUB_TOKEN}}
          label: 'Pepe'
          message: >
            Thank you for filing this issue.  We appreciate your feedback and will review the issue as soon as possible. 
            Remember, however, that GitHub isn't a mechanism for receiving support under any agreement or SLA. 
            If you require immediate assistance, contact Salesforce Customer Support.
      - name: log action output
        run: echo ${{steps.run_action.outputs.message}}
